# Generated by Django 5.0.6 on 2024-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('teachers_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject_specialization', models.CharField(max_length=20)),
                ('years_of_experience', models.IntegerField()),
                ('office_hours', models.IntegerField()),
                ('biography', models.TextField()),
                ('course_taught', models.CharField(max_length=20)),
            ],
        ),
    ]
