# Generated by Django 5.0.6 on 2024-07-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classroom',
        ),
    ]
